### ISSUE TITLE
Missing requirements

### ISSUE THREAD

**Issue by robertanto** [microsoft/esvit#25]
Hi!

I am trying to load esvit on Google Colaboratory with the following code:
```python3
!git clone https://github.com/microsoft/esvit.git
!pip install -r ./esvit/requirements.txt

import models.vision_transformer as vits
```
I got the following error:
```bash
...
[/usr/local/lib/python3.7/dist-packages/timm/models/layers/helpers.py](https://localhost:8080/#) in <module>
      4 """
      5 from itertools import repeat
----> 6 from torch._six import container_abcs
      7 
      8
ImportError: cannot import name 'container_abcs' from 'torch._six' (/usr/local/lib/python3.7/dist-packages/torch/_six.py)
```

which seems to be related to the torch version. However, downgrading torch (<1.11.0) I obtain errors on other torch imports.

Is there available a testing notebook?

**Comment by robertanto** [comment]
It works with torch v1.8.0 and torchvision v0.9.0.
